imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: fh_essentials.cache.redis.orm
        result_cache_driver:
            type: service
            id: fh_essentials.cache.redis.orm
        query_cache_driver:
            type: service
            id: fh_essentials.cache.redis.orm

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:         rotating_file
            path:         '%kernel.logs_dir%/%kernel.environment%.log'
            level:        debug
            max_files:    14
