imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: '%locale%' }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_proxies: ~
    session:
        save_path: '%session_dir%'
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:        [ FHAppBundle ]
    filters:
        cssrewrite:
            apply_to: '\.(css|scss|sass)$'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        mapping_types:
            enum: string
        server_version: 5.5
        schema_filter: '#^(?!fb__).*#'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
#        # Enable this for Doctrine mappings in your Infrastructure directory
#        mappings:
#            application:
#                type:       yml
#                is_bundle:  false
#                dir:        '%kernel.root_dir%/../src/FH/Infrastructure/Resources/config/doctrine'
#                prefix:     FH\Application\Model

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    port:      '%mailer_port%'
    spool:     { type: memory }

# Enable this for the doctrine redis cache configuration in config_test, config_staging, config_prod
# Your project name can be the same as the name of your (git) repository
#fh_essentials:
#    redis_cache:
#        namespace:  <your project name>
#        host:       '%redis_host%'
