parameters:
    database_driver:    pdo_mysql
    database_host:      127.0.0.1
    database_port:      ~
    database_name:      symfony
    database_user:      root
    database_password:  ~

    mailer_transport:   smtp
    mailer_host:        127.0.0.1
    mailer_user:        ~
    mailer_password:    ~
    mailer_port:        25

    redis_host:         localhost

    locale:             nl
    secret:             ThisTokenIsNotSoSecretChangeIt
    session_dir:        '%kernel.root_dir%/sessions'
