home:
    path:  /
    defaults: { _controller: fh_app.controller.main:homeAction }

app:
    path:  /app/{token}
    defaults: { _controller: fh_app.controller.main:appAction }

update:
    path:  /update-playlist/{token}
    defaults: { _controller: fh_app.controller.main:updatePlaylistAction }
